import type { Metadata } from "next";
import {DM_Sans} from "next/font/google";
import "./globals.css";


export const metadata: Metadata = {
  title: "Instance",
  description: "Generated by create next app",
};

export const dm_sans = DM_Sans({ subsets: ["latin"],weight: ["100", "200", "300", "400", "500", "600", "700"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dm_sans}antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
